name: Fullbright
main: com.applenick.Fullbright.Fullbright
version: ${project.version}-${git.commit.id.abbrev}
description: You can view the plugin at https://github.com/applenick/Fullbright
author: AppleNick